name: Create user branch and prompt base change

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, reopened]

permissions:
  contents: write
  issues: write

jobs:
  create-branch-and-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create ratatui feature branch
        if: endsWith(github.head_ref, '/ratatui')
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin
          git checkout -B ${{ github.head_ref }} origin/main
          git push origin ${{ github.head_ref }} --force

      - name: 💬 Comment on PR to change base branch
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello, please change your base branch to `${{ github.head_ref }}`.